FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir tensorflow[and-cuda] tensorflow_hub tensorflow_text

RUN pip uninstall -y tensorflow estimator keras && \
    pip install --no-cache-dir \
        tensorflow \
        tensorflow_text \
        tensorflow_datasets \
        einops

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
